# Generated by Django 2.2.5 on 2019-10-11 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=80)),
                ('room_id', models.CharField(max_length=50)),
                ('trans_mode', models.CharField(choices=[('SIMPLEX', 'Simplex'), ('HALF_DUPLEX', 'Half-Duplex'), ('DUPLEX', 'Duplex')], default=('DUPLEX', 'Duplex'), max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
